### ISSUE TITLE
I have isn't working properties panel after release diagram-js@7.4.0

### ISSUE THREAD

**Issue by okornilov** [bpmn-io/dmn-js-properties-panel#23]
After release diagram-js@7.4.0, I have isn't working properties panel because in package.json set verssion with '^'. 
This is very sad. Can you solve this problem?

**Comment by marstamm** [comment]
Hi @okornilov ,

we are aware of the issue and are fixing it with #22. There will be a patch release for `dmn-js-properties-panel` once it is merged.

**Comment by okornilov** [comment]
Thank you for answer. How to prevent it in future? Can you set versions in package.json without '^', so dependencies not resolved automatically? I'd like you set dependency version manually. This will allow you to avoid similar mistakes in the future.

**Comment by marstamm** [comment]
Hi,

Usually, minor updates should not break your application and we are currently working on fixing it. We will inform you once it is available.

In the meantime, if you want to use a specific  library version, you can set it in the `package.json` (`"diagram-js": "7.3.1"`), or use npm with the `save-exact` flag: `npm install diagram-js@7.3.1 --save-exact`.

**Comment by okornilov** [comment]
Thank you. I'll be waiting for the patch

**Comment by marstamm** [comment]
Hi @okornilov ,

we just released `dmn-js-properties-panel@0.6.2`, can you check if this update fixes the problems you are experiencing?

Cheers
Martin

**Comment by okornilov** [comment]
The problem isn't solved.

`unhandled error in event listener TypeError: Cannot read properties of null (reading 'labelTarget')
    at createGeneralTabGroups (CamundaPropertiesProvider.js:26)
    at CamundaPropertiesProvider.getTabs (CamundaPropertiesProvider.js:74)
    at PropertiesPanel.push../node_modules/dmn-js-properties-panel/lib/PropertiesPanel.js.PropertiesPanel.update (PropertiesPanel.js:396)
    at DrdAdapter.js:31
    at invokeFunction (EventBus.js:519)
    at EventBus.push../node_modules/diagram-js/lib/core/EventBus.js.EventBus._invokeListener (EventBus.js:371)
    at EventBus.push../node_modules/diagram-js/lib/core/EventBus.js.EventBus._invokeListeners (EventBus.js:352)
    at EventBus.push../node_modules/diagram-js/lib/core/EventBus.js.EventBus.fire (EventBus.js:313)
    at Selection.push../node_modules/diagram-js/lib/features/selection/Selection.js.Selection.select (Selection.js:104)
    at Selection.js:30`

**Comment by marstamm** [comment]
Hi,
just a quick update to let you know we are working on this. https://github.com/bpmn-io/diagram-js/pull/569 will fix the navigation issues with the properties panel.

**Comment by marstamm** [comment]
We just released `diagram-js@7.4.1`. With this release, I cannot reproduce the issue anymore, I hope that it fixes your Problem as well :slightly_smiling_face: 

Let me know if you encounter further problems and sorry for the inconvenience!

**Comment by okornilov** [comment]
The problem is solved. Thank you for your prompt help
